name: Check

on:
  pull_request:
    branches:
      - development
jobs:
  quality:
    name: Lint, Format, Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use NVM node version
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint check
        run: yarn lint

      - name: Format check
        run: yarn format

      - name: Run tests
        run: yarn test

  build_and_analyze:
    name: Build & Analyze Bundle Sizes
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Use NVM node version
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run build
        run: yarn build

      - name: Analyze bundle sizes
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        uses: transferwise/actions-next-bundle-analyzer@v2
        with:
          comment-strategy: "always"
